pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building my first Jenkins CI/CD Pipeline sub.....'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing my first Jenkins CI/CD Pipeline......'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying my first Jenkins CI/CD Pipeline......'
            }
        }
    }
}
